services:
  - type: web
    name: blitzapp
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start
    envVars:
      - key: reVDquNvieXDRQ2LBjBzwvqXOvq4p5d9
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true